// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "data/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// FileRepository is an autogenerated mock type for the FileRepository type
type FileRepository struct {
	mock.Mock
}

type FileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *FileRepository) EXPECT() *FileRepository_Expecter {
	return &FileRepository_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function with given fields: ctx, id
func (_m *FileRepository) DeleteFile(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileRepository_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type FileRepository_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *FileRepository_Expecter) DeleteFile(ctx interface{}, id interface{}) *FileRepository_DeleteFile_Call {
	return &FileRepository_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, id)}
}

func (_c *FileRepository_DeleteFile_Call) Run(run func(ctx context.Context, id string)) *FileRepository_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FileRepository_DeleteFile_Call) Return(_a0 error) *FileRepository_DeleteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileRepository_DeleteFile_Call) RunAndReturn(run func(context.Context, string) error) *FileRepository_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileByID provides a mock function with given fields: ctx, id
func (_m *FileRepository) GetFileByID(ctx context.Context, id string) (*models.FileMetadata, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFileByID")
	}

	var r0 *models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.FileMetadata, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.FileMetadata); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileRepository_GetFileByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileByID'
type FileRepository_GetFileByID_Call struct {
	*mock.Call
}

// GetFileByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *FileRepository_Expecter) GetFileByID(ctx interface{}, id interface{}) *FileRepository_GetFileByID_Call {
	return &FileRepository_GetFileByID_Call{Call: _e.mock.On("GetFileByID", ctx, id)}
}

func (_c *FileRepository_GetFileByID_Call) Run(run func(ctx context.Context, id string)) *FileRepository_GetFileByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FileRepository_GetFileByID_Call) Return(_a0 *models.FileMetadata, _a1 error) *FileRepository_GetFileByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileRepository_GetFileByID_Call) RunAndReturn(run func(context.Context, string) (*models.FileMetadata, error)) *FileRepository_GetFileByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileByPath provides a mock function with given fields: ctx, path, userID
func (_m *FileRepository) GetFileByPath(ctx context.Context, path string, userID string) (*models.FileMetadata, error) {
	ret := _m.Called(ctx, path, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFileByPath")
	}

	var r0 *models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.FileMetadata, error)); ok {
		return rf(ctx, path, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.FileMetadata); ok {
		r0 = rf(ctx, path, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, path, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileRepository_GetFileByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileByPath'
type FileRepository_GetFileByPath_Call struct {
	*mock.Call
}

// GetFileByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - userID string
func (_e *FileRepository_Expecter) GetFileByPath(ctx interface{}, path interface{}, userID interface{}) *FileRepository_GetFileByPath_Call {
	return &FileRepository_GetFileByPath_Call{Call: _e.mock.On("GetFileByPath", ctx, path, userID)}
}

func (_c *FileRepository_GetFileByPath_Call) Run(run func(ctx context.Context, path string, userID string)) *FileRepository_GetFileByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *FileRepository_GetFileByPath_Call) Return(_a0 *models.FileMetadata, _a1 error) *FileRepository_GetFileByPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileRepository_GetFileByPath_Call) RunAndReturn(run func(context.Context, string, string) (*models.FileMetadata, error)) *FileRepository_GetFileByPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileByStoragePath provides a mock function with given fields: ctx, storagePath
func (_m *FileRepository) GetFileByStoragePath(ctx context.Context, storagePath string) (*models.FileMetadata, error) {
	ret := _m.Called(ctx, storagePath)

	if len(ret) == 0 {
		panic("no return value specified for GetFileByStoragePath")
	}

	var r0 *models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.FileMetadata, error)); ok {
		return rf(ctx, storagePath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.FileMetadata); ok {
		r0 = rf(ctx, storagePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storagePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileRepository_GetFileByStoragePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileByStoragePath'
type FileRepository_GetFileByStoragePath_Call struct {
	*mock.Call
}

// GetFileByStoragePath is a helper method to define mock.On call
//   - ctx context.Context
//   - storagePath string
func (_e *FileRepository_Expecter) GetFileByStoragePath(ctx interface{}, storagePath interface{}) *FileRepository_GetFileByStoragePath_Call {
	return &FileRepository_GetFileByStoragePath_Call{Call: _e.mock.On("GetFileByStoragePath", ctx, storagePath)}
}

func (_c *FileRepository_GetFileByStoragePath_Call) Run(run func(ctx context.Context, storagePath string)) *FileRepository_GetFileByStoragePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FileRepository_GetFileByStoragePath_Call) Return(_a0 *models.FileMetadata, _a1 error) *FileRepository_GetFileByStoragePath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileRepository_GetFileByStoragePath_Call) RunAndReturn(run func(context.Context, string) (*models.FileMetadata, error)) *FileRepository_GetFileByStoragePath_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilesByFolderID provides a mock function with given fields: ctx, folderID
func (_m *FileRepository) GetFilesByFolderID(ctx context.Context, folderID string) ([]*models.FileMetadata, error) {
	ret := _m.Called(ctx, folderID)

	if len(ret) == 0 {
		panic("no return value specified for GetFilesByFolderID")
	}

	var r0 []*models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.FileMetadata, error)); ok {
		return rf(ctx, folderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.FileMetadata); ok {
		r0 = rf(ctx, folderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, folderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileRepository_GetFilesByFolderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilesByFolderID'
type FileRepository_GetFilesByFolderID_Call struct {
	*mock.Call
}

// GetFilesByFolderID is a helper method to define mock.On call
//   - ctx context.Context
//   - folderID string
func (_e *FileRepository_Expecter) GetFilesByFolderID(ctx interface{}, folderID interface{}) *FileRepository_GetFilesByFolderID_Call {
	return &FileRepository_GetFilesByFolderID_Call{Call: _e.mock.On("GetFilesByFolderID", ctx, folderID)}
}

func (_c *FileRepository_GetFilesByFolderID_Call) Run(run func(ctx context.Context, folderID string)) *FileRepository_GetFilesByFolderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FileRepository_GetFilesByFolderID_Call) Return(_a0 []*models.FileMetadata, _a1 error) *FileRepository_GetFilesByFolderID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileRepository_GetFilesByFolderID_Call) RunAndReturn(run func(context.Context, string) ([]*models.FileMetadata, error)) *FileRepository_GetFilesByFolderID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFile provides a mock function with given fields: ctx, metadata
func (_m *FileRepository) SaveFile(ctx context.Context, metadata *models.FileMetadata) (*models.FileMetadata, error) {
	ret := _m.Called(ctx, metadata)

	if len(ret) == 0 {
		panic("no return value specified for SaveFile")
	}

	var r0 *models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) (*models.FileMetadata, error)); ok {
		return rf(ctx, metadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) *models.FileMetadata); ok {
		r0 = rf(ctx, metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.FileMetadata) error); ok {
		r1 = rf(ctx, metadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileRepository_SaveFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFile'
type FileRepository_SaveFile_Call struct {
	*mock.Call
}

// SaveFile is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *models.FileMetadata
func (_e *FileRepository_Expecter) SaveFile(ctx interface{}, metadata interface{}) *FileRepository_SaveFile_Call {
	return &FileRepository_SaveFile_Call{Call: _e.mock.On("SaveFile", ctx, metadata)}
}

func (_c *FileRepository_SaveFile_Call) Run(run func(ctx context.Context, metadata *models.FileMetadata)) *FileRepository_SaveFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata))
	})
	return _c
}

func (_c *FileRepository_SaveFile_Call) Return(_a0 *models.FileMetadata, _a1 error) *FileRepository_SaveFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileRepository_SaveFile_Call) RunAndReturn(run func(context.Context, *models.FileMetadata) (*models.FileMetadata, error)) *FileRepository_SaveFile_Call {
	_c.Call.Return(run)
	return _c
}

// SearchFiles provides a mock function with given fields: ctx, userID, req
func (_m *FileRepository) SearchFiles(ctx context.Context, userID string, req *models.SearchRequest) ([]*models.FileMetadata, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for SearchFiles")
	}

	var r0 []*models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.SearchRequest) ([]*models.FileMetadata, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.SearchRequest) []*models.FileMetadata); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *models.SearchRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileRepository_SearchFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchFiles'
type FileRepository_SearchFiles_Call struct {
	*mock.Call
}

// SearchFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req *models.SearchRequest
func (_e *FileRepository_Expecter) SearchFiles(ctx interface{}, userID interface{}, req interface{}) *FileRepository_SearchFiles_Call {
	return &FileRepository_SearchFiles_Call{Call: _e.mock.On("SearchFiles", ctx, userID, req)}
}

func (_c *FileRepository_SearchFiles_Call) Run(run func(ctx context.Context, userID string, req *models.SearchRequest)) *FileRepository_SearchFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*models.SearchRequest))
	})
	return _c
}

func (_c *FileRepository_SearchFiles_Call) Return(_a0 []*models.FileMetadata, _a1 error) *FileRepository_SearchFiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileRepository_SearchFiles_Call) RunAndReturn(run func(context.Context, string, *models.SearchRequest) ([]*models.FileMetadata, error)) *FileRepository_SearchFiles_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFileByPath provides a mock function with given fields: ctx, metadata
func (_m *FileRepository) UpdateFileByPath(ctx context.Context, metadata *models.FileMetadata) (*models.FileMetadata, error) {
	ret := _m.Called(ctx, metadata)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFileByPath")
	}

	var r0 *models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) (*models.FileMetadata, error)); ok {
		return rf(ctx, metadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) *models.FileMetadata); ok {
		r0 = rf(ctx, metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.FileMetadata) error); ok {
		r1 = rf(ctx, metadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileRepository_UpdateFileByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFileByPath'
type FileRepository_UpdateFileByPath_Call struct {
	*mock.Call
}

// UpdateFileByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *models.FileMetadata
func (_e *FileRepository_Expecter) UpdateFileByPath(ctx interface{}, metadata interface{}) *FileRepository_UpdateFileByPath_Call {
	return &FileRepository_UpdateFileByPath_Call{Call: _e.mock.On("UpdateFileByPath", ctx, metadata)}
}

func (_c *FileRepository_UpdateFileByPath_Call) Run(run func(ctx context.Context, metadata *models.FileMetadata)) *FileRepository_UpdateFileByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata))
	})
	return _c
}

func (_c *FileRepository_UpdateFileByPath_Call) Return(_a0 *models.FileMetadata, _a1 error) *FileRepository_UpdateFileByPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileRepository_UpdateFileByPath_Call) RunAndReturn(run func(context.Context, *models.FileMetadata) (*models.FileMetadata, error)) *FileRepository_UpdateFileByPath_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileRepository creates a new instance of FileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileRepository {
	mock := &FileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
