// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "data/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// FileProcessingRepository is an autogenerated mock type for the FileProcessingRepository type
type FileProcessingRepository struct {
	mock.Mock
}

type FileProcessingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *FileProcessingRepository) EXPECT() *FileProcessingRepository_Expecter {
	return &FileProcessingRepository_Expecter{mock: &_m.Mock}
}

// DeleteProcessing provides a mock function with given fields: ctx, file
func (_m *FileProcessingRepository) DeleteProcessing(ctx context.Context, file *models.FileMetadata) error {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProcessing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) error); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileProcessingRepository_DeleteProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProcessing'
type FileProcessingRepository_DeleteProcessing_Call struct {
	*mock.Call
}

// DeleteProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - file *models.FileMetadata
func (_e *FileProcessingRepository_Expecter) DeleteProcessing(ctx interface{}, file interface{}) *FileProcessingRepository_DeleteProcessing_Call {
	return &FileProcessingRepository_DeleteProcessing_Call{Call: _e.mock.On("DeleteProcessing", ctx, file)}
}

func (_c *FileProcessingRepository_DeleteProcessing_Call) Run(run func(ctx context.Context, file *models.FileMetadata)) *FileProcessingRepository_DeleteProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata))
	})
	return _c
}

func (_c *FileProcessingRepository_DeleteProcessing_Call) Return(_a0 error) *FileProcessingRepository_DeleteProcessing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileProcessingRepository_DeleteProcessing_Call) RunAndReturn(run func(context.Context, *models.FileMetadata) error) *FileProcessingRepository_DeleteProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessingIsExists provides a mock function with given fields: ctx, file
func (_m *FileProcessingRepository) ProcessingIsExists(ctx context.Context, file *models.FileMetadata) (bool, error) {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for ProcessingIsExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) (bool, error)); ok {
		return rf(ctx, file)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) bool); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.FileMetadata) error); ok {
		r1 = rf(ctx, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileProcessingRepository_ProcessingIsExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessingIsExists'
type FileProcessingRepository_ProcessingIsExists_Call struct {
	*mock.Call
}

// ProcessingIsExists is a helper method to define mock.On call
//   - ctx context.Context
//   - file *models.FileMetadata
func (_e *FileProcessingRepository_Expecter) ProcessingIsExists(ctx interface{}, file interface{}) *FileProcessingRepository_ProcessingIsExists_Call {
	return &FileProcessingRepository_ProcessingIsExists_Call{Call: _e.mock.On("ProcessingIsExists", ctx, file)}
}

func (_c *FileProcessingRepository_ProcessingIsExists_Call) Run(run func(ctx context.Context, file *models.FileMetadata)) *FileProcessingRepository_ProcessingIsExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata))
	})
	return _c
}

func (_c *FileProcessingRepository_ProcessingIsExists_Call) Return(_a0 bool, _a1 error) *FileProcessingRepository_ProcessingIsExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileProcessingRepository_ProcessingIsExists_Call) RunAndReturn(run func(context.Context, *models.FileMetadata) (bool, error)) *FileProcessingRepository_ProcessingIsExists_Call {
	_c.Call.Return(run)
	return _c
}

// SetProcessing provides a mock function with given fields: ctx, file
func (_m *FileProcessingRepository) SetProcessing(ctx context.Context, file *models.FileMetadata) error {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for SetProcessing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) error); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileProcessingRepository_SetProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetProcessing'
type FileProcessingRepository_SetProcessing_Call struct {
	*mock.Call
}

// SetProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - file *models.FileMetadata
func (_e *FileProcessingRepository_Expecter) SetProcessing(ctx interface{}, file interface{}) *FileProcessingRepository_SetProcessing_Call {
	return &FileProcessingRepository_SetProcessing_Call{Call: _e.mock.On("SetProcessing", ctx, file)}
}

func (_c *FileProcessingRepository_SetProcessing_Call) Run(run func(ctx context.Context, file *models.FileMetadata)) *FileProcessingRepository_SetProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata))
	})
	return _c
}

func (_c *FileProcessingRepository_SetProcessing_Call) Return(_a0 error) *FileProcessingRepository_SetProcessing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileProcessingRepository_SetProcessing_Call) RunAndReturn(run func(context.Context, *models.FileMetadata) error) *FileProcessingRepository_SetProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileProcessingRepository creates a new instance of FileProcessingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileProcessingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileProcessingRepository {
	mock := &FileProcessingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
