// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "data/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// FolderRepository is an autogenerated mock type for the FolderRepository type
type FolderRepository struct {
	mock.Mock
}

type FolderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *FolderRepository) EXPECT() *FolderRepository_Expecter {
	return &FolderRepository_Expecter{mock: &_m.Mock}
}

// DeleteFolder provides a mock function with given fields: ctx, id
func (_m *FolderRepository) DeleteFolder(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFolder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FolderRepository_DeleteFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFolder'
type FolderRepository_DeleteFolder_Call struct {
	*mock.Call
}

// DeleteFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *FolderRepository_Expecter) DeleteFolder(ctx interface{}, id interface{}) *FolderRepository_DeleteFolder_Call {
	return &FolderRepository_DeleteFolder_Call{Call: _e.mock.On("DeleteFolder", ctx, id)}
}

func (_c *FolderRepository_DeleteFolder_Call) Run(run func(ctx context.Context, id string)) *FolderRepository_DeleteFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FolderRepository_DeleteFolder_Call) Return(_a0 error) *FolderRepository_DeleteFolder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FolderRepository_DeleteFolder_Call) RunAndReturn(run func(context.Context, string) error) *FolderRepository_DeleteFolder_Call {
	_c.Call.Return(run)
	return _c
}

// GetFolderByID provides a mock function with given fields: ctx, id
func (_m *FolderRepository) GetFolderByID(ctx context.Context, id string) (*models.Folder, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFolderByID")
	}

	var r0 *models.Folder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Folder, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Folder); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FolderRepository_GetFolderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFolderByID'
type FolderRepository_GetFolderByID_Call struct {
	*mock.Call
}

// GetFolderByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *FolderRepository_Expecter) GetFolderByID(ctx interface{}, id interface{}) *FolderRepository_GetFolderByID_Call {
	return &FolderRepository_GetFolderByID_Call{Call: _e.mock.On("GetFolderByID", ctx, id)}
}

func (_c *FolderRepository_GetFolderByID_Call) Run(run func(ctx context.Context, id string)) *FolderRepository_GetFolderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FolderRepository_GetFolderByID_Call) Return(_a0 *models.Folder, _a1 error) *FolderRepository_GetFolderByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FolderRepository_GetFolderByID_Call) RunAndReturn(run func(context.Context, string) (*models.Folder, error)) *FolderRepository_GetFolderByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFolderByParentID provides a mock function with given fields: ctx, parentID
func (_m *FolderRepository) GetFolderByParentID(ctx context.Context, parentID string) ([]*models.Folder, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetFolderByParentID")
	}

	var r0 []*models.Folder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.Folder, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.Folder); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Folder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FolderRepository_GetFolderByParentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFolderByParentID'
type FolderRepository_GetFolderByParentID_Call struct {
	*mock.Call
}

// GetFolderByParentID is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID string
func (_e *FolderRepository_Expecter) GetFolderByParentID(ctx interface{}, parentID interface{}) *FolderRepository_GetFolderByParentID_Call {
	return &FolderRepository_GetFolderByParentID_Call{Call: _e.mock.On("GetFolderByParentID", ctx, parentID)}
}

func (_c *FolderRepository_GetFolderByParentID_Call) Run(run func(ctx context.Context, parentID string)) *FolderRepository_GetFolderByParentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FolderRepository_GetFolderByParentID_Call) Return(_a0 []*models.Folder, _a1 error) *FolderRepository_GetFolderByParentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FolderRepository_GetFolderByParentID_Call) RunAndReturn(run func(context.Context, string) ([]*models.Folder, error)) *FolderRepository_GetFolderByParentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRootFolder provides a mock function with given fields: ctx, userID
func (_m *FolderRepository) GetRootFolder(ctx context.Context, userID string) (*models.Folder, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRootFolder")
	}

	var r0 *models.Folder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Folder, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Folder); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FolderRepository_GetRootFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRootFolder'
type FolderRepository_GetRootFolder_Call struct {
	*mock.Call
}

// GetRootFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *FolderRepository_Expecter) GetRootFolder(ctx interface{}, userID interface{}) *FolderRepository_GetRootFolder_Call {
	return &FolderRepository_GetRootFolder_Call{Call: _e.mock.On("GetRootFolder", ctx, userID)}
}

func (_c *FolderRepository_GetRootFolder_Call) Run(run func(ctx context.Context, userID string)) *FolderRepository_GetRootFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FolderRepository_GetRootFolder_Call) Return(_a0 *models.Folder, _a1 error) *FolderRepository_GetRootFolder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FolderRepository_GetRootFolder_Call) RunAndReturn(run func(context.Context, string) (*models.Folder, error)) *FolderRepository_GetRootFolder_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFolder provides a mock function with given fields: ctx, folder
func (_m *FolderRepository) SaveFolder(ctx context.Context, folder *models.Folder) (*models.Folder, error) {
	ret := _m.Called(ctx, folder)

	if len(ret) == 0 {
		panic("no return value specified for SaveFolder")
	}

	var r0 *models.Folder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Folder) (*models.Folder, error)); ok {
		return rf(ctx, folder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Folder) *models.Folder); ok {
		r0 = rf(ctx, folder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Folder) error); ok {
		r1 = rf(ctx, folder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FolderRepository_SaveFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFolder'
type FolderRepository_SaveFolder_Call struct {
	*mock.Call
}

// SaveFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - folder *models.Folder
func (_e *FolderRepository_Expecter) SaveFolder(ctx interface{}, folder interface{}) *FolderRepository_SaveFolder_Call {
	return &FolderRepository_SaveFolder_Call{Call: _e.mock.On("SaveFolder", ctx, folder)}
}

func (_c *FolderRepository_SaveFolder_Call) Run(run func(ctx context.Context, folder *models.Folder)) *FolderRepository_SaveFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Folder))
	})
	return _c
}

func (_c *FolderRepository_SaveFolder_Call) Return(_a0 *models.Folder, _a1 error) *FolderRepository_SaveFolder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FolderRepository_SaveFolder_Call) RunAndReturn(run func(context.Context, *models.Folder) (*models.Folder, error)) *FolderRepository_SaveFolder_Call {
	_c.Call.Return(run)
	return _c
}

// NewFolderRepository creates a new instance of FolderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFolderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FolderRepository {
	mock := &FolderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
