// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	models "storage/internal/models"
)

// StorageRepository is an autogenerated mock type for the StorageRepository type
type StorageRepository struct {
	mock.Mock
}

type StorageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageRepository) EXPECT() *StorageRepository_Expecter {
	return &StorageRepository_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function with given fields: ctx, path
func (_m *StorageRepository) DeleteFile(ctx context.Context, path string) error {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageRepository_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type StorageRepository_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *StorageRepository_Expecter) DeleteFile(ctx interface{}, path interface{}) *StorageRepository_DeleteFile_Call {
	return &StorageRepository_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, path)}
}

func (_c *StorageRepository_DeleteFile_Call) Run(run func(ctx context.Context, path string)) *StorageRepository_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StorageRepository_DeleteFile_Call) Return(_a0 error) *StorageRepository_DeleteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageRepository_DeleteFile_Call) RunAndReturn(run func(context.Context, string) error) *StorageRepository_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function with given fields: ctx, path
func (_m *StorageRepository) ReadFile(ctx context.Context, path string) (io.Reader, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 io.Reader
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.Reader, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.Reader); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageRepository_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type StorageRepository_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *StorageRepository_Expecter) ReadFile(ctx interface{}, path interface{}) *StorageRepository_ReadFile_Call {
	return &StorageRepository_ReadFile_Call{Call: _e.mock.On("ReadFile", ctx, path)}
}

func (_c *StorageRepository_ReadFile_Call) Run(run func(ctx context.Context, path string)) *StorageRepository_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StorageRepository_ReadFile_Call) Return(_a0 io.Reader, _a1 error) *StorageRepository_ReadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageRepository_ReadFile_Call) RunAndReturn(run func(context.Context, string) (io.Reader, error)) *StorageRepository_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFile provides a mock function with given fields: ctx, metadata, data
func (_m *StorageRepository) UploadFile(ctx context.Context, metadata *models.FileMetadata, data io.Reader) (*models.FileMetadata, error) {
	ret := _m.Called(ctx, metadata, data)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 *models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata, io.Reader) (*models.FileMetadata, error)); ok {
		return rf(ctx, metadata, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata, io.Reader) *models.FileMetadata); ok {
		r0 = rf(ctx, metadata, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.FileMetadata, io.Reader) error); ok {
		r1 = rf(ctx, metadata, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageRepository_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type StorageRepository_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *models.FileMetadata
//   - data io.Reader
func (_e *StorageRepository_Expecter) UploadFile(ctx interface{}, metadata interface{}, data interface{}) *StorageRepository_UploadFile_Call {
	return &StorageRepository_UploadFile_Call{Call: _e.mock.On("UploadFile", ctx, metadata, data)}
}

func (_c *StorageRepository_UploadFile_Call) Run(run func(ctx context.Context, metadata *models.FileMetadata, data io.Reader)) *StorageRepository_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata), args[2].(io.Reader))
	})
	return _c
}

func (_c *StorageRepository_UploadFile_Call) Return(_a0 *models.FileMetadata, _a1 error) *StorageRepository_UploadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageRepository_UploadFile_Call) RunAndReturn(run func(context.Context, *models.FileMetadata, io.Reader) (*models.FileMetadata, error)) *StorageRepository_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageRepository creates a new instance of StorageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageRepository {
	mock := &StorageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
