// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "storage/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// UploadProcessingRepository is an autogenerated mock type for the UploadProcessingRepository type
type UploadProcessingRepository struct {
	mock.Mock
}

type UploadProcessingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UploadProcessingRepository) EXPECT() *UploadProcessingRepository_Expecter {
	return &UploadProcessingRepository_Expecter{mock: &_m.Mock}
}

// DeleteProcessing provides a mock function with given fields: ctx, file
func (_m *UploadProcessingRepository) DeleteProcessing(ctx context.Context, file *models.FileMetadata) error {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProcessing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) error); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadProcessingRepository_DeleteProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProcessing'
type UploadProcessingRepository_DeleteProcessing_Call struct {
	*mock.Call
}

// DeleteProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - file *models.FileMetadata
func (_e *UploadProcessingRepository_Expecter) DeleteProcessing(ctx interface{}, file interface{}) *UploadProcessingRepository_DeleteProcessing_Call {
	return &UploadProcessingRepository_DeleteProcessing_Call{Call: _e.mock.On("DeleteProcessing", ctx, file)}
}

func (_c *UploadProcessingRepository_DeleteProcessing_Call) Run(run func(ctx context.Context, file *models.FileMetadata)) *UploadProcessingRepository_DeleteProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata))
	})
	return _c
}

func (_c *UploadProcessingRepository_DeleteProcessing_Call) Return(_a0 error) *UploadProcessingRepository_DeleteProcessing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UploadProcessingRepository_DeleteProcessing_Call) RunAndReturn(run func(context.Context, *models.FileMetadata) error) *UploadProcessingRepository_DeleteProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessingIsExists provides a mock function with given fields: ctx, file
func (_m *UploadProcessingRepository) ProcessingIsExists(ctx context.Context, file *models.FileMetadata) (bool, error) {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for ProcessingIsExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) (bool, error)); ok {
		return rf(ctx, file)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) bool); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.FileMetadata) error); ok {
		r1 = rf(ctx, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadProcessingRepository_ProcessingIsExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessingIsExists'
type UploadProcessingRepository_ProcessingIsExists_Call struct {
	*mock.Call
}

// ProcessingIsExists is a helper method to define mock.On call
//   - ctx context.Context
//   - file *models.FileMetadata
func (_e *UploadProcessingRepository_Expecter) ProcessingIsExists(ctx interface{}, file interface{}) *UploadProcessingRepository_ProcessingIsExists_Call {
	return &UploadProcessingRepository_ProcessingIsExists_Call{Call: _e.mock.On("ProcessingIsExists", ctx, file)}
}

func (_c *UploadProcessingRepository_ProcessingIsExists_Call) Run(run func(ctx context.Context, file *models.FileMetadata)) *UploadProcessingRepository_ProcessingIsExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata))
	})
	return _c
}

func (_c *UploadProcessingRepository_ProcessingIsExists_Call) Return(_a0 bool, _a1 error) *UploadProcessingRepository_ProcessingIsExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UploadProcessingRepository_ProcessingIsExists_Call) RunAndReturn(run func(context.Context, *models.FileMetadata) (bool, error)) *UploadProcessingRepository_ProcessingIsExists_Call {
	_c.Call.Return(run)
	return _c
}

// SetProcessing provides a mock function with given fields: ctx, file
func (_m *UploadProcessingRepository) SetProcessing(ctx context.Context, file *models.FileMetadata) error {
	ret := _m.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for SetProcessing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) error); ok {
		r0 = rf(ctx, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadProcessingRepository_SetProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetProcessing'
type UploadProcessingRepository_SetProcessing_Call struct {
	*mock.Call
}

// SetProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - file *models.FileMetadata
func (_e *UploadProcessingRepository_Expecter) SetProcessing(ctx interface{}, file interface{}) *UploadProcessingRepository_SetProcessing_Call {
	return &UploadProcessingRepository_SetProcessing_Call{Call: _e.mock.On("SetProcessing", ctx, file)}
}

func (_c *UploadProcessingRepository_SetProcessing_Call) Run(run func(ctx context.Context, file *models.FileMetadata)) *UploadProcessingRepository_SetProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata))
	})
	return _c
}

func (_c *UploadProcessingRepository_SetProcessing_Call) Return(_a0 error) *UploadProcessingRepository_SetProcessing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UploadProcessingRepository_SetProcessing_Call) RunAndReturn(run func(context.Context, *models.FileMetadata) error) *UploadProcessingRepository_SetProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// UserIDByFile provides a mock function with given fields: ctx, id
func (_m *UploadProcessingRepository) UserIDByFile(ctx context.Context, id string) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserIDByFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadProcessingRepository_UserIDByFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserIDByFile'
type UploadProcessingRepository_UserIDByFile_Call struct {
	*mock.Call
}

// UserIDByFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UploadProcessingRepository_Expecter) UserIDByFile(ctx interface{}, id interface{}) *UploadProcessingRepository_UserIDByFile_Call {
	return &UploadProcessingRepository_UserIDByFile_Call{Call: _e.mock.On("UserIDByFile", ctx, id)}
}

func (_c *UploadProcessingRepository_UserIDByFile_Call) Run(run func(ctx context.Context, id string)) *UploadProcessingRepository_UserIDByFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UploadProcessingRepository_UserIDByFile_Call) Return(_a0 string, _a1 error) *UploadProcessingRepository_UserIDByFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UploadProcessingRepository_UserIDByFile_Call) RunAndReturn(run func(context.Context, string) (string, error)) *UploadProcessingRepository_UserIDByFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewUploadProcessingRepository creates a new instance of UploadProcessingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUploadProcessingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UploadProcessingRepository {
	mock := &UploadProcessingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
