// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "storage/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// FileAdapter is an autogenerated mock type for the FileAdapter type
type FileAdapter struct {
	mock.Mock
}

type FileAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *FileAdapter) EXPECT() *FileAdapter_Expecter {
	return &FileAdapter_Expecter{mock: &_m.Mock}
}

// PushFailedFile provides a mock function with given fields: ctx, metadata, err
func (_m *FileAdapter) PushFailedFile(ctx context.Context, metadata *models.FileMetadata, err error) error {
	ret := _m.Called(ctx, metadata, err)

	if len(ret) == 0 {
		panic("no return value specified for PushFailedFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata, error) error); ok {
		r0 = rf(ctx, metadata, err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileAdapter_PushFailedFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushFailedFile'
type FileAdapter_PushFailedFile_Call struct {
	*mock.Call
}

// PushFailedFile is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *models.FileMetadata
//   - err error
func (_e *FileAdapter_Expecter) PushFailedFile(ctx interface{}, metadata interface{}, err interface{}) *FileAdapter_PushFailedFile_Call {
	return &FileAdapter_PushFailedFile_Call{Call: _e.mock.On("PushFailedFile", ctx, metadata, err)}
}

func (_c *FileAdapter_PushFailedFile_Call) Run(run func(ctx context.Context, metadata *models.FileMetadata, err error)) *FileAdapter_PushFailedFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata), args[2].(error))
	})
	return _c
}

func (_c *FileAdapter_PushFailedFile_Call) Return(_a0 error) *FileAdapter_PushFailedFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileAdapter_PushFailedFile_Call) RunAndReturn(run func(context.Context, *models.FileMetadata, error) error) *FileAdapter_PushFailedFile_Call {
	_c.Call.Return(run)
	return _c
}

// PushUploadedFile provides a mock function with given fields: ctx, metadata
func (_m *FileAdapter) PushUploadedFile(ctx context.Context, metadata *models.FileMetadata) error {
	ret := _m.Called(ctx, metadata)

	if len(ret) == 0 {
		panic("no return value specified for PushUploadedFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) error); ok {
		r0 = rf(ctx, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileAdapter_PushUploadedFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushUploadedFile'
type FileAdapter_PushUploadedFile_Call struct {
	*mock.Call
}

// PushUploadedFile is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *models.FileMetadata
func (_e *FileAdapter_Expecter) PushUploadedFile(ctx interface{}, metadata interface{}) *FileAdapter_PushUploadedFile_Call {
	return &FileAdapter_PushUploadedFile_Call{Call: _e.mock.On("PushUploadedFile", ctx, metadata)}
}

func (_c *FileAdapter_PushUploadedFile_Call) Run(run func(ctx context.Context, metadata *models.FileMetadata)) *FileAdapter_PushUploadedFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata))
	})
	return _c
}

func (_c *FileAdapter_PushUploadedFile_Call) Return(_a0 error) *FileAdapter_PushUploadedFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileAdapter_PushUploadedFile_Call) RunAndReturn(run func(context.Context, *models.FileMetadata) error) *FileAdapter_PushUploadedFile_Call {
	_c.Call.Return(run)
	return _c
}

// PushUploadingFile provides a mock function with given fields: ctx, metadata
func (_m *FileAdapter) PushUploadingFile(ctx context.Context, metadata *models.FileMetadata) error {
	ret := _m.Called(ctx, metadata)

	if len(ret) == 0 {
		panic("no return value specified for PushUploadingFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) error); ok {
		r0 = rf(ctx, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileAdapter_PushUploadingFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushUploadingFile'
type FileAdapter_PushUploadingFile_Call struct {
	*mock.Call
}

// PushUploadingFile is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *models.FileMetadata
func (_e *FileAdapter_Expecter) PushUploadingFile(ctx interface{}, metadata interface{}) *FileAdapter_PushUploadingFile_Call {
	return &FileAdapter_PushUploadingFile_Call{Call: _e.mock.On("PushUploadingFile", ctx, metadata)}
}

func (_c *FileAdapter_PushUploadingFile_Call) Run(run func(ctx context.Context, metadata *models.FileMetadata)) *FileAdapter_PushUploadingFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata))
	})
	return _c
}

func (_c *FileAdapter_PushUploadingFile_Call) Return(_a0 error) *FileAdapter_PushUploadingFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileAdapter_PushUploadingFile_Call) RunAndReturn(run func(context.Context, *models.FileMetadata) error) *FileAdapter_PushUploadingFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileAdapter creates a new instance of FileAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileAdapter {
	mock := &FileAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
