// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UploadingAdapter is an autogenerated mock type for the UploadingAdapter type
type UploadingAdapter struct {
	mock.Mock
}

type UploadingAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *UploadingAdapter) EXPECT() *UploadingAdapter_Expecter {
	return &UploadingAdapter_Expecter{mock: &_m.Mock}
}

// PushCancelUploading provides a mock function with given fields: ctx, fileID
func (_m *UploadingAdapter) PushCancelUploading(ctx context.Context, fileID string) error {
	ret := _m.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for PushCancelUploading")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, fileID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadingAdapter_PushCancelUploading_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushCancelUploading'
type UploadingAdapter_PushCancelUploading_Call struct {
	*mock.Call
}

// PushCancelUploading is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *UploadingAdapter_Expecter) PushCancelUploading(ctx interface{}, fileID interface{}) *UploadingAdapter_PushCancelUploading_Call {
	return &UploadingAdapter_PushCancelUploading_Call{Call: _e.mock.On("PushCancelUploading", ctx, fileID)}
}

func (_c *UploadingAdapter_PushCancelUploading_Call) Run(run func(ctx context.Context, fileID string)) *UploadingAdapter_PushCancelUploading_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UploadingAdapter_PushCancelUploading_Call) Return(_a0 error) *UploadingAdapter_PushCancelUploading_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UploadingAdapter_PushCancelUploading_Call) RunAndReturn(run func(context.Context, string) error) *UploadingAdapter_PushCancelUploading_Call {
	_c.Call.Return(run)
	return _c
}

// NewUploadingAdapter creates a new instance of UploadingAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUploadingAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *UploadingAdapter {
	mock := &UploadingAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
