// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "data/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// CollectorService is an autogenerated mock type for the CollectorService type
type CollectorService struct {
	mock.Mock
}

type CollectorService_Expecter struct {
	mock *mock.Mock
}

func (_m *CollectorService) EXPECT() *CollectorService_Expecter {
	return &CollectorService_Expecter{mock: &_m.Mock}
}

// DeleteFolder provides a mock function with given fields: ctx, id
func (_m *CollectorService) DeleteFolder(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFolder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CollectorService_DeleteFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFolder'
type CollectorService_DeleteFolder_Call struct {
	*mock.Call
}

// DeleteFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CollectorService_Expecter) DeleteFolder(ctx interface{}, id interface{}) *CollectorService_DeleteFolder_Call {
	return &CollectorService_DeleteFolder_Call{Call: _e.mock.On("DeleteFolder", ctx, id)}
}

func (_c *CollectorService_DeleteFolder_Call) Run(run func(ctx context.Context, id string)) *CollectorService_DeleteFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CollectorService_DeleteFolder_Call) Return(_a0 error) *CollectorService_DeleteFolder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CollectorService_DeleteFolder_Call) RunAndReturn(run func(context.Context, string) error) *CollectorService_DeleteFolder_Call {
	_c.Call.Return(run)
	return _c
}

// GetFolderTree provides a mock function with given fields: ctx, parentID
func (_m *CollectorService) GetFolderTree(ctx context.Context, parentID string) (*models.FolderTree, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetFolderTree")
	}

	var r0 *models.FolderTree
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.FolderTree, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.FolderTree); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FolderTree)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CollectorService_GetFolderTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFolderTree'
type CollectorService_GetFolderTree_Call struct {
	*mock.Call
}

// GetFolderTree is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID string
func (_e *CollectorService_Expecter) GetFolderTree(ctx interface{}, parentID interface{}) *CollectorService_GetFolderTree_Call {
	return &CollectorService_GetFolderTree_Call{Call: _e.mock.On("GetFolderTree", ctx, parentID)}
}

func (_c *CollectorService_GetFolderTree_Call) Run(run func(ctx context.Context, parentID string)) *CollectorService_GetFolderTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CollectorService_GetFolderTree_Call) Return(_a0 *models.FolderTree, _a1 error) *CollectorService_GetFolderTree_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CollectorService_GetFolderTree_Call) RunAndReturn(run func(context.Context, string) (*models.FolderTree, error)) *CollectorService_GetFolderTree_Call {
	_c.Call.Return(run)
	return _c
}

// NewCollectorService creates a new instance of CollectorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCollectorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CollectorService {
	mock := &CollectorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
