// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "data/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// FileService is an autogenerated mock type for the FileService type
type FileService struct {
	mock.Mock
}

type FileService_Expecter struct {
	mock *mock.Mock
}

func (_m *FileService) EXPECT() *FileService_Expecter {
	return &FileService_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function with given fields: ctx, id
func (_m *FileService) DeleteFile(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileService_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type FileService_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *FileService_Expecter) DeleteFile(ctx interface{}, id interface{}) *FileService_DeleteFile_Call {
	return &FileService_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, id)}
}

func (_c *FileService_DeleteFile_Call) Run(run func(ctx context.Context, id string)) *FileService_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FileService_DeleteFile_Call) Return(_a0 error) *FileService_DeleteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileService_DeleteFile_Call) RunAndReturn(run func(context.Context, string) error) *FileService_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// FileFailed provides a mock function with given fields: ctx, metadata, err
func (_m *FileService) FileFailed(ctx context.Context, metadata *models.FileMetadata, err error) error {
	ret := _m.Called(ctx, metadata, err)

	if len(ret) == 0 {
		panic("no return value specified for FileFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata, error) error); ok {
		r0 = rf(ctx, metadata, err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileService_FileFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileFailed'
type FileService_FileFailed_Call struct {
	*mock.Call
}

// FileFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *models.FileMetadata
//   - err error
func (_e *FileService_Expecter) FileFailed(ctx interface{}, metadata interface{}, err interface{}) *FileService_FileFailed_Call {
	return &FileService_FileFailed_Call{Call: _e.mock.On("FileFailed", ctx, metadata, err)}
}

func (_c *FileService_FileFailed_Call) Run(run func(ctx context.Context, metadata *models.FileMetadata, err error)) *FileService_FileFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata), args[2].(error))
	})
	return _c
}

func (_c *FileService_FileFailed_Call) Return(_a0 error) *FileService_FileFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileService_FileFailed_Call) RunAndReturn(run func(context.Context, *models.FileMetadata, error) error) *FileService_FileFailed_Call {
	_c.Call.Return(run)
	return _c
}

// FileUploaded provides a mock function with given fields: ctx, metadata
func (_m *FileService) FileUploaded(ctx context.Context, metadata *models.FileMetadata) error {
	ret := _m.Called(ctx, metadata)

	if len(ret) == 0 {
		panic("no return value specified for FileUploaded")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) error); ok {
		r0 = rf(ctx, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileService_FileUploaded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileUploaded'
type FileService_FileUploaded_Call struct {
	*mock.Call
}

// FileUploaded is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *models.FileMetadata
func (_e *FileService_Expecter) FileUploaded(ctx interface{}, metadata interface{}) *FileService_FileUploaded_Call {
	return &FileService_FileUploaded_Call{Call: _e.mock.On("FileUploaded", ctx, metadata)}
}

func (_c *FileService_FileUploaded_Call) Run(run func(ctx context.Context, metadata *models.FileMetadata)) *FileService_FileUploaded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata))
	})
	return _c
}

func (_c *FileService_FileUploaded_Call) Return(_a0 error) *FileService_FileUploaded_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileService_FileUploaded_Call) RunAndReturn(run func(context.Context, *models.FileMetadata) error) *FileService_FileUploaded_Call {
	_c.Call.Return(run)
	return _c
}

// FileUploading provides a mock function with given fields: ctx, metadata
func (_m *FileService) FileUploading(ctx context.Context, metadata *models.FileMetadata) error {
	ret := _m.Called(ctx, metadata)

	if len(ret) == 0 {
		panic("no return value specified for FileUploading")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) error); ok {
		r0 = rf(ctx, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileService_FileUploading_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileUploading'
type FileService_FileUploading_Call struct {
	*mock.Call
}

// FileUploading is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *models.FileMetadata
func (_e *FileService_Expecter) FileUploading(ctx interface{}, metadata interface{}) *FileService_FileUploading_Call {
	return &FileService_FileUploading_Call{Call: _e.mock.On("FileUploading", ctx, metadata)}
}

func (_c *FileService_FileUploading_Call) Run(run func(ctx context.Context, metadata *models.FileMetadata)) *FileService_FileUploading_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata))
	})
	return _c
}

func (_c *FileService_FileUploading_Call) Return(_a0 error) *FileService_FileUploading_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileService_FileUploading_Call) RunAndReturn(run func(context.Context, *models.FileMetadata) error) *FileService_FileUploading_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileByID provides a mock function with given fields: ctx, id
func (_m *FileService) GetFileByID(ctx context.Context, id string) (*models.FileMetadata, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFileByID")
	}

	var r0 *models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.FileMetadata, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.FileMetadata); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileService_GetFileByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileByID'
type FileService_GetFileByID_Call struct {
	*mock.Call
}

// GetFileByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *FileService_Expecter) GetFileByID(ctx interface{}, id interface{}) *FileService_GetFileByID_Call {
	return &FileService_GetFileByID_Call{Call: _e.mock.On("GetFileByID", ctx, id)}
}

func (_c *FileService_GetFileByID_Call) Run(run func(ctx context.Context, id string)) *FileService_GetFileByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FileService_GetFileByID_Call) Return(_a0 *models.FileMetadata, _a1 error) *FileService_GetFileByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileService_GetFileByID_Call) RunAndReturn(run func(context.Context, string) (*models.FileMetadata, error)) *FileService_GetFileByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileByStoragePath provides a mock function with given fields: ctx, storagePath
func (_m *FileService) GetFileByStoragePath(ctx context.Context, storagePath string) (*models.FileMetadata, error) {
	ret := _m.Called(ctx, storagePath)

	if len(ret) == 0 {
		panic("no return value specified for GetFileByStoragePath")
	}

	var r0 *models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.FileMetadata, error)); ok {
		return rf(ctx, storagePath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.FileMetadata); ok {
		r0 = rf(ctx, storagePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storagePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileService_GetFileByStoragePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileByStoragePath'
type FileService_GetFileByStoragePath_Call struct {
	*mock.Call
}

// GetFileByStoragePath is a helper method to define mock.On call
//   - ctx context.Context
//   - storagePath string
func (_e *FileService_Expecter) GetFileByStoragePath(ctx interface{}, storagePath interface{}) *FileService_GetFileByStoragePath_Call {
	return &FileService_GetFileByStoragePath_Call{Call: _e.mock.On("GetFileByStoragePath", ctx, storagePath)}
}

func (_c *FileService_GetFileByStoragePath_Call) Run(run func(ctx context.Context, storagePath string)) *FileService_GetFileByStoragePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FileService_GetFileByStoragePath_Call) Return(_a0 *models.FileMetadata, _a1 error) *FileService_GetFileByStoragePath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileService_GetFileByStoragePath_Call) RunAndReturn(run func(context.Context, string) (*models.FileMetadata, error)) *FileService_GetFileByStoragePath_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilesByFolderID provides a mock function with given fields: ctx, folderID
func (_m *FileService) GetFilesByFolderID(ctx context.Context, folderID string) ([]*models.FileMetadata, error) {
	ret := _m.Called(ctx, folderID)

	if len(ret) == 0 {
		panic("no return value specified for GetFilesByFolderID")
	}

	var r0 []*models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.FileMetadata, error)); ok {
		return rf(ctx, folderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.FileMetadata); ok {
		r0 = rf(ctx, folderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, folderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileService_GetFilesByFolderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilesByFolderID'
type FileService_GetFilesByFolderID_Call struct {
	*mock.Call
}

// GetFilesByFolderID is a helper method to define mock.On call
//   - ctx context.Context
//   - folderID string
func (_e *FileService_Expecter) GetFilesByFolderID(ctx interface{}, folderID interface{}) *FileService_GetFilesByFolderID_Call {
	return &FileService_GetFilesByFolderID_Call{Call: _e.mock.On("GetFilesByFolderID", ctx, folderID)}
}

func (_c *FileService_GetFilesByFolderID_Call) Run(run func(ctx context.Context, folderID string)) *FileService_GetFilesByFolderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FileService_GetFilesByFolderID_Call) Return(_a0 []*models.FileMetadata, _a1 error) *FileService_GetFilesByFolderID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileService_GetFilesByFolderID_Call) RunAndReturn(run func(context.Context, string) ([]*models.FileMetadata, error)) *FileService_GetFilesByFolderID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFile provides a mock function with given fields: ctx, metadata
func (_m *FileService) SaveFile(ctx context.Context, metadata *models.FileMetadata) (*models.FileMetadata, error) {
	ret := _m.Called(ctx, metadata)

	if len(ret) == 0 {
		panic("no return value specified for SaveFile")
	}

	var r0 *models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) (*models.FileMetadata, error)); ok {
		return rf(ctx, metadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) *models.FileMetadata); ok {
		r0 = rf(ctx, metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.FileMetadata) error); ok {
		r1 = rf(ctx, metadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileService_SaveFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFile'
type FileService_SaveFile_Call struct {
	*mock.Call
}

// SaveFile is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *models.FileMetadata
func (_e *FileService_Expecter) SaveFile(ctx interface{}, metadata interface{}) *FileService_SaveFile_Call {
	return &FileService_SaveFile_Call{Call: _e.mock.On("SaveFile", ctx, metadata)}
}

func (_c *FileService_SaveFile_Call) Run(run func(ctx context.Context, metadata *models.FileMetadata)) *FileService_SaveFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata))
	})
	return _c
}

func (_c *FileService_SaveFile_Call) Return(_a0 *models.FileMetadata, _a1 error) *FileService_SaveFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileService_SaveFile_Call) RunAndReturn(run func(context.Context, *models.FileMetadata) (*models.FileMetadata, error)) *FileService_SaveFile_Call {
	_c.Call.Return(run)
	return _c
}

// SearchFiles provides a mock function with given fields: ctx, req
func (_m *FileService) SearchFiles(ctx context.Context, req *models.SearchRequest) ([]*models.FileMetadata, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SearchFiles")
	}

	var r0 []*models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.SearchRequest) ([]*models.FileMetadata, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.SearchRequest) []*models.FileMetadata); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.SearchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileService_SearchFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchFiles'
type FileService_SearchFiles_Call struct {
	*mock.Call
}

// SearchFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - req *models.SearchRequest
func (_e *FileService_Expecter) SearchFiles(ctx interface{}, req interface{}) *FileService_SearchFiles_Call {
	return &FileService_SearchFiles_Call{Call: _e.mock.On("SearchFiles", ctx, req)}
}

func (_c *FileService_SearchFiles_Call) Run(run func(ctx context.Context, req *models.SearchRequest)) *FileService_SearchFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.SearchRequest))
	})
	return _c
}

func (_c *FileService_SearchFiles_Call) Return(_a0 []*models.FileMetadata, _a1 error) *FileService_SearchFiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileService_SearchFiles_Call) RunAndReturn(run func(context.Context, *models.SearchRequest) ([]*models.FileMetadata, error)) *FileService_SearchFiles_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileService creates a new instance of FileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileService {
	mock := &FileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
