// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "data/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// FolderService is an autogenerated mock type for the FolderService type
type FolderService struct {
	mock.Mock
}

type FolderService_Expecter struct {
	mock *mock.Mock
}

func (_m *FolderService) EXPECT() *FolderService_Expecter {
	return &FolderService_Expecter{mock: &_m.Mock}
}

// DeleteFolder provides a mock function with given fields: ctx, id
func (_m *FolderService) DeleteFolder(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFolder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FolderService_DeleteFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFolder'
type FolderService_DeleteFolder_Call struct {
	*mock.Call
}

// DeleteFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *FolderService_Expecter) DeleteFolder(ctx interface{}, id interface{}) *FolderService_DeleteFolder_Call {
	return &FolderService_DeleteFolder_Call{Call: _e.mock.On("DeleteFolder", ctx, id)}
}

func (_c *FolderService_DeleteFolder_Call) Run(run func(ctx context.Context, id string)) *FolderService_DeleteFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FolderService_DeleteFolder_Call) Return(_a0 error) *FolderService_DeleteFolder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FolderService_DeleteFolder_Call) RunAndReturn(run func(context.Context, string) error) *FolderService_DeleteFolder_Call {
	_c.Call.Return(run)
	return _c
}

// GetFolderByID provides a mock function with given fields: ctx, id
func (_m *FolderService) GetFolderByID(ctx context.Context, id string) (*models.Folder, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFolderByID")
	}

	var r0 *models.Folder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Folder, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Folder); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FolderService_GetFolderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFolderByID'
type FolderService_GetFolderByID_Call struct {
	*mock.Call
}

// GetFolderByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *FolderService_Expecter) GetFolderByID(ctx interface{}, id interface{}) *FolderService_GetFolderByID_Call {
	return &FolderService_GetFolderByID_Call{Call: _e.mock.On("GetFolderByID", ctx, id)}
}

func (_c *FolderService_GetFolderByID_Call) Run(run func(ctx context.Context, id string)) *FolderService_GetFolderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FolderService_GetFolderByID_Call) Return(_a0 *models.Folder, _a1 error) *FolderService_GetFolderByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FolderService_GetFolderByID_Call) RunAndReturn(run func(context.Context, string) (*models.Folder, error)) *FolderService_GetFolderByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFoldersByParentID provides a mock function with given fields: ctx, parentID
func (_m *FolderService) GetFoldersByParentID(ctx context.Context, parentID string) ([]*models.Folder, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetFoldersByParentID")
	}

	var r0 []*models.Folder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.Folder, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.Folder); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Folder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FolderService_GetFoldersByParentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFoldersByParentID'
type FolderService_GetFoldersByParentID_Call struct {
	*mock.Call
}

// GetFoldersByParentID is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID string
func (_e *FolderService_Expecter) GetFoldersByParentID(ctx interface{}, parentID interface{}) *FolderService_GetFoldersByParentID_Call {
	return &FolderService_GetFoldersByParentID_Call{Call: _e.mock.On("GetFoldersByParentID", ctx, parentID)}
}

func (_c *FolderService_GetFoldersByParentID_Call) Run(run func(ctx context.Context, parentID string)) *FolderService_GetFoldersByParentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FolderService_GetFoldersByParentID_Call) Return(_a0 []*models.Folder, _a1 error) *FolderService_GetFoldersByParentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FolderService_GetFoldersByParentID_Call) RunAndReturn(run func(context.Context, string) ([]*models.Folder, error)) *FolderService_GetFoldersByParentID_Call {
	_c.Call.Return(run)
	return _c
}

// RootFolder provides a mock function with given fields: ctx, userID
func (_m *FolderService) RootFolder(ctx context.Context, userID string) (*models.Folder, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RootFolder")
	}

	var r0 *models.Folder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Folder, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Folder); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FolderService_RootFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RootFolder'
type FolderService_RootFolder_Call struct {
	*mock.Call
}

// RootFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *FolderService_Expecter) RootFolder(ctx interface{}, userID interface{}) *FolderService_RootFolder_Call {
	return &FolderService_RootFolder_Call{Call: _e.mock.On("RootFolder", ctx, userID)}
}

func (_c *FolderService_RootFolder_Call) Run(run func(ctx context.Context, userID string)) *FolderService_RootFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *FolderService_RootFolder_Call) Return(_a0 *models.Folder, _a1 error) *FolderService_RootFolder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FolderService_RootFolder_Call) RunAndReturn(run func(context.Context, string) (*models.Folder, error)) *FolderService_RootFolder_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFolder provides a mock function with given fields: ctx, folder
func (_m *FolderService) SaveFolder(ctx context.Context, folder *models.Folder) (*models.Folder, error) {
	ret := _m.Called(ctx, folder)

	if len(ret) == 0 {
		panic("no return value specified for SaveFolder")
	}

	var r0 *models.Folder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Folder) (*models.Folder, error)); ok {
		return rf(ctx, folder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Folder) *models.Folder); ok {
		r0 = rf(ctx, folder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Folder) error); ok {
		r1 = rf(ctx, folder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FolderService_SaveFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFolder'
type FolderService_SaveFolder_Call struct {
	*mock.Call
}

// SaveFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - folder *models.Folder
func (_e *FolderService_Expecter) SaveFolder(ctx interface{}, folder interface{}) *FolderService_SaveFolder_Call {
	return &FolderService_SaveFolder_Call{Call: _e.mock.On("SaveFolder", ctx, folder)}
}

func (_c *FolderService_SaveFolder_Call) Run(run func(ctx context.Context, folder *models.Folder)) *FolderService_SaveFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Folder))
	})
	return _c
}

func (_c *FolderService_SaveFolder_Call) Return(_a0 *models.Folder, _a1 error) *FolderService_SaveFolder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FolderService_SaveFolder_Call) RunAndReturn(run func(context.Context, *models.Folder) (*models.Folder, error)) *FolderService_SaveFolder_Call {
	_c.Call.Return(run)
	return _c
}

// NewFolderService creates a new instance of FolderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFolderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FolderService {
	mock := &FolderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
