// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "storage/internal/models"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// DeleteFileMetadata provides a mock function with given fields: ctx, id
func (_m *Client) DeleteFileMetadata(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFileMetadata")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_DeleteFileMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFileMetadata'
type Client_DeleteFileMetadata_Call struct {
	*mock.Call
}

// DeleteFileMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Client_Expecter) DeleteFileMetadata(ctx interface{}, id interface{}) *Client_DeleteFileMetadata_Call {
	return &Client_DeleteFileMetadata_Call{Call: _e.mock.On("DeleteFileMetadata", ctx, id)}
}

func (_c *Client_DeleteFileMetadata_Call) Run(run func(ctx context.Context, id string)) *Client_DeleteFileMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_DeleteFileMetadata_Call) Return(_a0 error) *Client_DeleteFileMetadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_DeleteFileMetadata_Call) RunAndReturn(run func(context.Context, string) error) *Client_DeleteFileMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileMetadata provides a mock function with given fields: ctx, id
func (_m *Client) GetFileMetadata(ctx context.Context, id string) (*models.FileMetadata, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFileMetadata")
	}

	var r0 *models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.FileMetadata, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.FileMetadata); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetFileMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileMetadata'
type Client_GetFileMetadata_Call struct {
	*mock.Call
}

// GetFileMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Client_Expecter) GetFileMetadata(ctx interface{}, id interface{}) *Client_GetFileMetadata_Call {
	return &Client_GetFileMetadata_Call{Call: _e.mock.On("GetFileMetadata", ctx, id)}
}

func (_c *Client_GetFileMetadata_Call) Run(run func(ctx context.Context, id string)) *Client_GetFileMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetFileMetadata_Call) Return(_a0 *models.FileMetadata, _a1 error) *Client_GetFileMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetFileMetadata_Call) RunAndReturn(run func(context.Context, string) (*models.FileMetadata, error)) *Client_GetFileMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetFolderByID provides a mock function with given fields: ctx, id
func (_m *Client) GetFolderByID(ctx context.Context, id string) (*models.Folder, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFolderByID")
	}

	var r0 *models.Folder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Folder, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Folder); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetFolderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFolderByID'
type Client_GetFolderByID_Call struct {
	*mock.Call
}

// GetFolderByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Client_Expecter) GetFolderByID(ctx interface{}, id interface{}) *Client_GetFolderByID_Call {
	return &Client_GetFolderByID_Call{Call: _e.mock.On("GetFolderByID", ctx, id)}
}

func (_c *Client_GetFolderByID_Call) Run(run func(ctx context.Context, id string)) *Client_GetFolderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetFolderByID_Call) Return(_a0 *models.Folder, _a1 error) *Client_GetFolderByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetFolderByID_Call) RunAndReturn(run func(context.Context, string) (*models.Folder, error)) *Client_GetFolderByID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFileMetadata provides a mock function with given fields: ctx, metadata
func (_m *Client) SaveFileMetadata(ctx context.Context, metadata *models.FileMetadata) (*models.FileMetadata, error) {
	ret := _m.Called(ctx, metadata)

	if len(ret) == 0 {
		panic("no return value specified for SaveFileMetadata")
	}

	var r0 *models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) (*models.FileMetadata, error)); ok {
		return rf(ctx, metadata)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata) *models.FileMetadata); ok {
		r0 = rf(ctx, metadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.FileMetadata) error); ok {
		r1 = rf(ctx, metadata)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_SaveFileMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFileMetadata'
type Client_SaveFileMetadata_Call struct {
	*mock.Call
}

// SaveFileMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *models.FileMetadata
func (_e *Client_Expecter) SaveFileMetadata(ctx interface{}, metadata interface{}) *Client_SaveFileMetadata_Call {
	return &Client_SaveFileMetadata_Call{Call: _e.mock.On("SaveFileMetadata", ctx, metadata)}
}

func (_c *Client_SaveFileMetadata_Call) Run(run func(ctx context.Context, metadata *models.FileMetadata)) *Client_SaveFileMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata))
	})
	return _c
}

func (_c *Client_SaveFileMetadata_Call) Return(_a0 *models.FileMetadata, _a1 error) *Client_SaveFileMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_SaveFileMetadata_Call) RunAndReturn(run func(context.Context, *models.FileMetadata) (*models.FileMetadata, error)) *Client_SaveFileMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
