// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	models "storage/internal/models"
)

// StorageService is an autogenerated mock type for the StorageService type
type StorageService struct {
	mock.Mock
}

type StorageService_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageService) EXPECT() *StorageService_Expecter {
	return &StorageService_Expecter{mock: &_m.Mock}
}

// CancelUpload provides a mock function with given fields: ctx, id
func (_m *StorageService) CancelUpload(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CancelUpload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageService_CancelUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelUpload'
type StorageService_CancelUpload_Call struct {
	*mock.Call
}

// CancelUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *StorageService_Expecter) CancelUpload(ctx interface{}, id interface{}) *StorageService_CancelUpload_Call {
	return &StorageService_CancelUpload_Call{Call: _e.mock.On("CancelUpload", ctx, id)}
}

func (_c *StorageService_CancelUpload_Call) Run(run func(ctx context.Context, id string)) *StorageService_CancelUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StorageService_CancelUpload_Call) Return(_a0 error) *StorageService_CancelUpload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageService_CancelUpload_Call) RunAndReturn(run func(context.Context, string) error) *StorageService_CancelUpload_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields: ctx
func (_m *StorageService) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageService_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type StorageService_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StorageService_Expecter) Close(ctx interface{}) *StorageService_Close_Call {
	return &StorageService_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *StorageService_Close_Call) Run(run func(ctx context.Context)) *StorageService_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *StorageService_Close_Call) Return(_a0 error) *StorageService_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageService_Close_Call) RunAndReturn(run func(context.Context) error) *StorageService_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFile provides a mock function with given fields: ctx, id
func (_m *StorageService) DeleteFile(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageService_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type StorageService_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *StorageService_Expecter) DeleteFile(ctx interface{}, id interface{}) *StorageService_DeleteFile_Call {
	return &StorageService_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, id)}
}

func (_c *StorageService_DeleteFile_Call) Run(run func(ctx context.Context, id string)) *StorageService_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StorageService_DeleteFile_Call) Return(_a0 error) *StorageService_DeleteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageService_DeleteFile_Call) RunAndReturn(run func(context.Context, string) error) *StorageService_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadFile provides a mock function with given fields: ctx, id
func (_m *StorageService) DownloadFile(ctx context.Context, id string) (*models.FileMetadata, io.Reader, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DownloadFile")
	}

	var r0 *models.FileMetadata
	var r1 io.Reader
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.FileMetadata, io.Reader, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.FileMetadata); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) io.Reader); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.Reader)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// StorageService_DownloadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadFile'
type StorageService_DownloadFile_Call struct {
	*mock.Call
}

// DownloadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *StorageService_Expecter) DownloadFile(ctx interface{}, id interface{}) *StorageService_DownloadFile_Call {
	return &StorageService_DownloadFile_Call{Call: _e.mock.On("DownloadFile", ctx, id)}
}

func (_c *StorageService_DownloadFile_Call) Run(run func(ctx context.Context, id string)) *StorageService_DownloadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StorageService_DownloadFile_Call) Return(_a0 *models.FileMetadata, _a1 io.Reader, _a2 error) *StorageService_DownloadFile_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *StorageService_DownloadFile_Call) RunAndReturn(run func(context.Context, string) (*models.FileMetadata, io.Reader, error)) *StorageService_DownloadFile_Call {
	_c.Call.Return(run)
	return _c
}

// HandleCancelUpload provides a mock function with given fields: ctx, id
func (_m *StorageService) HandleCancelUpload(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for HandleCancelUpload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageService_HandleCancelUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCancelUpload'
type StorageService_HandleCancelUpload_Call struct {
	*mock.Call
}

// HandleCancelUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *StorageService_Expecter) HandleCancelUpload(ctx interface{}, id interface{}) *StorageService_HandleCancelUpload_Call {
	return &StorageService_HandleCancelUpload_Call{Call: _e.mock.On("HandleCancelUpload", ctx, id)}
}

func (_c *StorageService_HandleCancelUpload_Call) Run(run func(ctx context.Context, id string)) *StorageService_HandleCancelUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StorageService_HandleCancelUpload_Call) Return(_a0 error) *StorageService_HandleCancelUpload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageService_HandleCancelUpload_Call) RunAndReturn(run func(context.Context, string) error) *StorageService_HandleCancelUpload_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFile provides a mock function with given fields: ctx, metadata, data
func (_m *StorageService) UploadFile(ctx context.Context, metadata *models.FileMetadata, data io.Reader) (*models.FileMetadata, error) {
	ret := _m.Called(ctx, metadata, data)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 *models.FileMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata, io.Reader) (*models.FileMetadata, error)); ok {
		return rf(ctx, metadata, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.FileMetadata, io.Reader) *models.FileMetadata); ok {
		r0 = rf(ctx, metadata, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FileMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.FileMetadata, io.Reader) error); ok {
		r1 = rf(ctx, metadata, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageService_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type StorageService_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *models.FileMetadata
//   - data io.Reader
func (_e *StorageService_Expecter) UploadFile(ctx interface{}, metadata interface{}, data interface{}) *StorageService_UploadFile_Call {
	return &StorageService_UploadFile_Call{Call: _e.mock.On("UploadFile", ctx, metadata, data)}
}

func (_c *StorageService_UploadFile_Call) Run(run func(ctx context.Context, metadata *models.FileMetadata, data io.Reader)) *StorageService_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FileMetadata), args[2].(io.Reader))
	})
	return _c
}

func (_c *StorageService_UploadFile_Call) Return(_a0 *models.FileMetadata, _a1 error) *StorageService_UploadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageService_UploadFile_Call) RunAndReturn(run func(context.Context, *models.FileMetadata, io.Reader) (*models.FileMetadata, error)) *StorageService_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageService creates a new instance of StorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageService {
	mock := &StorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
